version: '2'
services:
  db:
    image: postgres
    env_file:
      - docker.env
  nginxservice:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    restart: always
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile_django
    env_file:
      - docker.env
    command: >
      bash -c "python manage.py migrate --settings=SFIAGenerator.settings.docker
      && python manage.py collectstatic --noinput --settings=SFIAGenerator.settings.docker
      && gunicorn SFIAGenerator.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code

    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  .:
  static_volume: